baseURL = 'https://cybercelery.github.io'
languageCode = 'en-us'
theme = 'coming-soon'


[params]
    title = "Celeridad Tech Blog" 
    description = "A refreshed blog site is on its way!"
    favicon = ""
    message = "COMING SOON!" 
    release = "April 20, 2025"
    background = "" 
